#应用日志配置
logging:
    file:
        path: d:/logs

#Keycloak配置
keycloak:
    realm: keycloak-examples-vanilla
    auth-server-url: http://127.0.0.1:8090/auth
    ssl-required: external
    #resource即是clientId
    resource: xmodule2-examples-keycloak-vanilla
    confidential-port: 0
    credentials:
        secret: 1af1850a-01ba-40a5-8569-8cb28f5ee341
    policy-enforcer-config:
        on-deny-redirect-to: /403

keycloak-admin:
    server-url: ${keycloak.auth-server-url}
    username: admin
    password: 123456
    
spring:
    datasource:
        #默认数据源配置
        default: 
            username: root
            password: 123456
            url: jdbc:mysql://127.0.0.1:3306/xmodule?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true