package com.penglecode.xmodule.security.oauth2.examples.upms.model;

import com.penglecode.xmodule.common.codegen.Id;
import com.penglecode.xmodule.common.codegen.Model;
import com.penglecode.xmodule.common.support.BaseModel;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * UPMS资源 (upms_resource) 实体类
 * 
 * @author Mybatis-Generator
 * @date	2019年12月21日 下午 12:39:02
 */
@Model(name="UPMS资源", alias="Resource")
public class UpmsResource implements BaseModel<UpmsResource> {
     
    private static final long serialVersionUID = 1L;

    /** 资源id */
    @Id
    private Long resourceId;

    /** 资源名称 */
    private String resourceName;

    /** 父级资源id */
    private Long parentResourceId;

    /** 是否是应用的根节点：1-是，0-否 */
    private Boolean appRootResource;

    /** 资源URL */
    private String resourceUrl;

    /** 资源类型：0-系统资源,1-普通资源 */
    private Integer resourceType;

    /** HTTP方法(GET,POST,DELETE,PUT) */
    private String httpMethod;

    /** 功能类型：0-菜单，1-按钮 */
    private Integer actionType;

    /** 兄弟节点间的排序号,asc排序 */
    private Integer siblingsIndex;

    /** 资源菜单ICON(font-awesome类名) */
    private String resourceIcon;

    /** 是否是首页：1-是，0-否 */
    private Boolean indexPage;

    /** 创建时间 */
    private String createTime;

    /** 创建者,用户表id */
    private Long createBy;

    /** 更新时间 */
    private String updateTime;

    /** 更新者,用户表的id */
    private Long updateBy;

    public Long getResourceId() {
        return resourceId;
    }

    public void setResourceId(Long resourceId) {
        this.resourceId = resourceId;
    }

    public String getResourceName() {
        return resourceName;
    }

    public void setResourceName(String resourceName) {
        this.resourceName = resourceName;
    }

    public Long getParentResourceId() {
        return parentResourceId;
    }

    public void setParentResourceId(Long parentResourceId) {
        this.parentResourceId = parentResourceId;
    }

    public Boolean getAppRootResource() {
        return appRootResource;
    }

    public void setAppRootResource(Boolean appRootResource) {
        this.appRootResource = appRootResource;
    }

    public String getResourceUrl() {
        return resourceUrl;
    }

    public void setResourceUrl(String resourceUrl) {
        this.resourceUrl = resourceUrl;
    }

    public Integer getResourceType() {
        return resourceType;
    }

    public void setResourceType(Integer resourceType) {
        this.resourceType = resourceType;
    }

    public String getHttpMethod() {
        return httpMethod;
    }

    public void setHttpMethod(String httpMethod) {
        this.httpMethod = httpMethod;
    }

    public Integer getActionType() {
        return actionType;
    }

    public void setActionType(Integer actionType) {
        this.actionType = actionType;
    }

    public Integer getSiblingsIndex() {
        return siblingsIndex;
    }

    public void setSiblingsIndex(Integer siblingsIndex) {
        this.siblingsIndex = siblingsIndex;
    }

    public String getResourceIcon() {
        return resourceIcon;
    }

    public void setResourceIcon(String resourceIcon) {
        this.resourceIcon = resourceIcon;
    }

    public Boolean getIndexPage() {
        return indexPage;
    }

    public void setIndexPage(Boolean indexPage) {
        this.indexPage = indexPage;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public Long getCreateBy() {
        return createBy;
    }

    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    public Long getUpdateBy() {
        return updateBy;
    }

    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    public MapBuilder mapBuilder() {
        return new MapBuilder();
    }

    /**
     * Auto generated by Mybatis Generator
     */
    public class MapBuilder {
         
        private final Map<String, Object> modelProperties = new LinkedHashMap<String,Object>();

        MapBuilder() {
            
        }

        public MapBuilder withResourceId(Long ... resourceId) {
            modelProperties.put("resourceId", BaseModel.first(resourceId, getResourceId()));
            return this;
        }

        public MapBuilder withResourceName(String ... resourceName) {
            modelProperties.put("resourceName", BaseModel.first(resourceName, getResourceName()));
            return this;
        }

        public MapBuilder withParentResourceId(Long ... parentResourceId) {
            modelProperties.put("parentResourceId", BaseModel.first(parentResourceId, getParentResourceId()));
            return this;
        }

        public MapBuilder withAppRootResource(Boolean ... appRootResource) {
            modelProperties.put("appRootResource", BaseModel.first(appRootResource, getAppRootResource()));
            return this;
        }

        public MapBuilder withResourceUrl(String ... resourceUrl) {
            modelProperties.put("resourceUrl", BaseModel.first(resourceUrl, getResourceUrl()));
            return this;
        }

        public MapBuilder withResourceType(Integer ... resourceType) {
            modelProperties.put("resourceType", BaseModel.first(resourceType, getResourceType()));
            return this;
        }

        public MapBuilder withHttpMethod(String ... httpMethod) {
            modelProperties.put("httpMethod", BaseModel.first(httpMethod, getHttpMethod()));
            return this;
        }

        public MapBuilder withActionType(Integer ... actionType) {
            modelProperties.put("actionType", BaseModel.first(actionType, getActionType()));
            return this;
        }

        public MapBuilder withSiblingsIndex(Integer ... siblingsIndex) {
            modelProperties.put("siblingsIndex", BaseModel.first(siblingsIndex, getSiblingsIndex()));
            return this;
        }

        public MapBuilder withResourceIcon(String ... resourceIcon) {
            modelProperties.put("resourceIcon", BaseModel.first(resourceIcon, getResourceIcon()));
            return this;
        }

        public MapBuilder withIndexPage(Boolean ... indexPage) {
            modelProperties.put("indexPage", BaseModel.first(indexPage, getIndexPage()));
            return this;
        }

        public MapBuilder withCreateTime(String ... createTime) {
            modelProperties.put("createTime", BaseModel.first(createTime, getCreateTime()));
            return this;
        }

        public MapBuilder withCreateBy(Long ... createBy) {
            modelProperties.put("createBy", BaseModel.first(createBy, getCreateBy()));
            return this;
        }

        public MapBuilder withUpdateTime(String ... updateTime) {
            modelProperties.put("updateTime", BaseModel.first(updateTime, getUpdateTime()));
            return this;
        }

        public MapBuilder withUpdateBy(Long ... updateBy) {
            modelProperties.put("updateBy", BaseModel.first(updateBy, getUpdateBy()));
            return this;
        }

        public Map<String, Object> build() {
            return modelProperties;
        }
    }
}