#应用日志配置
logging:
    file:
        path: /usr/local/xmodule2/logs

spring:
    keycloak:
        admin:
            server-url: http://127.0.0.1:8090/auth
            username: admin
            password: 123456